name: Run Solutions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Setup Git
      run: |
        git config --global user.email "leo@dumbartonserum.com";git config --global user.name "Leo Dumbarton"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run solutions
      run: |
        python collective_run.py
    - name: Create Comparison Table
      run: |
        pip install pandas tabulate
        python comptable.py
    - name: Commit results
      run: |
        git add runs && git commit -m "update results" && git push
